
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'user_touchpoints_attribution_template'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  user_touchpoints_attribution_template:
    # Applies to all files under models/example/
    user_journey:
      materialized: ephemeral

vars:
  # Any events before this date get ignored
  start_date: '2021-06-01'
  
  # Any domains in this list are ignored and not added ot the final list. Typically include test accounts.
  domains_to_ignore: ('rudder.com', 'rudderabs.com', 'rudderstack.co', 'rudderlabs.slack.com', 'asdfasdf.com', 'test.com')

  # Variable to consolidate top page calls.  You may have hundreds of pages on your site and ideally we should only consider those. Only these pages are considered. This can be customized as per the need and event.
  top_tracks_sources: ('add_a_product', 'landing_page_a', '', 'blog', 'home', 'check-out')

  # If a page doesn't fall under one of the top_tracks_sources, it defaults to the below page name
  default_tracks_touch: 'others'
  
  # These email domains are not treated as enterprise domains, and rather left alone as emails. 
  generic_domain_patterns: ('%gmail%', '%yahoo%', '%qq%', '%outlook%', '%hotmail%', '%rediff%')
  
  # If we want our data to be at email level and not at domain level, we can use below variable by uncommenting and comment above one.
  # generic_domain_patterns: ('%*%')
  
  # If any of the touches need to be dropped, we can do so using this parameter.  In this example, we have mutliple touchpoints in the same process so we will ignore those that are redundant.
  touches_to_ignore: ('marketing_newsletter_sent', 'marketing_campaign_sent', 'marketing_newsletter_clicked', 'marketing_campaign_clicked', 'signup', 'others', 'login', 'profile')
